"""empty message

Revision ID: 20093af38243
Revises: 762c2011e5dc
Create Date: 2020-06-29 15:29:01.376696

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '20093af38243'
down_revision = '762c2011e5dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('diagfile', sa.String(length=200), nullable=False),
    sa.Column('adk', sa.String(length=100), nullable=False),
    sa.Column('tracecheck', sa.String(length=100), nullable=True),
    sa.Column('build_package', sa.String(length=200), nullable=False),
    sa.Column('probdate', sa.String(length=100), nullable=False),
    sa.Column('probtime', sa.String(length=100), nullable=False),
    sa.Column('trxcomp', sa.String(length=100), nullable=True),
    sa.Column('analysis', sa.String(length=1000), nullable=False),
    sa.Column('jira', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('reboots', sa.String(length=100), nullable=True),
    sa.Column('fix_build', sa.String(length=100), nullable=True),
    sa.Column('detected', sa.String(length=100), nullable=True),
    sa.Column('assigned', sa.String(length=100), nullable=True),
    sa.Column('device_error', sa.String(length=200), nullable=False),
    sa.Column('gsa', sa.String(length=200), nullable=False),
    sa.Column('size', sa.String(length=100), nullable=True),
    sa.Column('hwtype', sa.String(length=200), nullable=False),
    sa.Column('motherboard', sa.String(length=200), nullable=False),
    sa.Column('sub_category', sa.String(length=100), nullable=True),
    sa.Column('rse_state', sa.String(length=100), nullable=False),
    sa.Column('store_num', sa.String(length=100), nullable=True),
    sa.Column('lane_num', sa.String(length=100), nullable=True),
    sa.Column('dbmanager', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('manual_analysis', 'date_time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('manual_analysis', 'date_time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.drop_table('upload_analysis')
    # ### end Alembic commands ###
