"""empty message

Revision ID: 2ccaa56c94d4
Revises: f7e6a85fc766
Create Date: 2020-07-12 12:42:41.209070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ccaa56c94d4'
down_revision = 'f7e6a85fc766'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rse_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('store', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=500), nullable=True),
    sa.Column('lane', sa.String(length=500), nullable=True),
    sa.Column('device', sa.String(length=500), nullable=True),
    sa.Column('rse_date', sa.String(length=500), nullable=True),
    sa.Column('rse_time', sa.String(length=500), nullable=True),
    sa.Column('tender_state', sa.String(length=500), nullable=True),
    sa.Column('state', sa.String(length=500), nullable=True),
    sa.Column('diagfile_name', sa.String(length=500), nullable=True),
    sa.Column('build', sa.String(length=500), nullable=True),
    sa.Column('analysis', sa.String(length=1000), nullable=True),
    sa.Column('jira', sa.String(length=500), nullable=True),
    sa.Column('Category', sa.String(length=500), nullable=True),
    sa.Column('types_of_reboot', sa.String(length=500), nullable=True),
    sa.Column('gsa_version', sa.String(length=500), nullable=True),
    sa.Column('device_error', sa.String(length=500), nullable=True),
    sa.Column('assign', sa.String(length=500), nullable=True),
    sa.Column('second_review', sa.String(length=500), nullable=True),
    sa.Column('null_data', sa.String(length=500), nullable=True),
    sa.Column('jira_or_gsa', sa.String(length=500), nullable=True),
    sa.Column('operational_review', sa.String(length=500), nullable=True),
    sa.Column('hwtype', sa.String(length=500), nullable=True),
    sa.Column('motherboard', sa.String(length=500), nullable=True),
    sa.Column('operational_reviewed_by', sa.String(length=500), nullable=True),
    sa.Column('sa_server', sa.String(length=500), nullable=True),
    sa.Column('data', sa.String(length=500), nullable=True),
    sa.Column('adk', sa.String(length=500), nullable=True),
    sa.Column('ps_package', sa.String(length=500), nullable=True),
    sa.Column('fix_version', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rse_reports')
    # ### end Alembic commands ###
