"""empty message

Revision ID: 3a9bcae8f98a
Revises: 20093af38243
Create Date: 2020-07-05 15:46:02.957369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a9bcae8f98a'
down_revision = '20093af38243'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_analysis_test',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_analysis_test')
    # ### end Alembic commands ###
