"""empty message

Revision ID: 540cded65af7
Revises: 3a9bcae8f98a
Create Date: 2020-07-05 15:56:20.053295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '540cded65af7'
down_revision = '3a9bcae8f98a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('upload_analysis_test')
    op.add_column('upload_analysis', sa.Column('associated_jira', sa.String(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('build', sa.String(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('dbmgr', sa.String(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('diagfile_name', sa.String(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('full_mini', sa.String(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('gsa_version', sa.String(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('hw_type', sa.String(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('lanenum', sa.String(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('storenum', sa.String(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('trace_check', sa.String(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('trx_comp', sa.String(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('type_reboot', sa.String(length=100), nullable=True))
    op.drop_column('upload_analysis', 'tracecheck')
    op.drop_column('upload_analysis', 'hwtype')
    op.drop_column('upload_analysis', 'reboots')
    op.drop_column('upload_analysis', 'jira')
    op.drop_column('upload_analysis', 'store_num')
    op.drop_column('upload_analysis', 'lane_num')
    op.drop_column('upload_analysis', 'diagfile')
    op.drop_column('upload_analysis', 'size')
    op.drop_column('upload_analysis', 'dbmanager')
    op.drop_column('upload_analysis', 'trxcomp')
    op.drop_column('upload_analysis', 'gsa')
    op.drop_column('upload_analysis', 'build_package')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('upload_analysis', sa.Column('build_package', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('gsa', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('trxcomp', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('dbmanager', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('size', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('diagfile', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('lane_num', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('store_num', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('jira', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('reboots', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('upload_analysis', sa.Column('hwtype', mysql.VARCHAR(length=200), nullable=False))
    op.add_column('upload_analysis', sa.Column('tracecheck', mysql.VARCHAR(length=100), nullable=True))
    op.drop_column('upload_analysis', 'type_reboot')
    op.drop_column('upload_analysis', 'trx_comp')
    op.drop_column('upload_analysis', 'trace_check')
    op.drop_column('upload_analysis', 'storenum')
    op.drop_column('upload_analysis', 'lanenum')
    op.drop_column('upload_analysis', 'hw_type')
    op.drop_column('upload_analysis', 'gsa_version')
    op.drop_column('upload_analysis', 'full_mini')
    op.drop_column('upload_analysis', 'diagfile_name')
    op.drop_column('upload_analysis', 'dbmgr')
    op.drop_column('upload_analysis', 'build')
    op.drop_column('upload_analysis', 'associated_jira')
    op.create_table('upload_analysis_test',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
