"""empty message

Revision ID: 7f9988f912d8
Revises: 540cded65af7
Create Date: 2020-07-05 16:00:24.364599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7f9988f912d8'
down_revision = '540cded65af7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_analysis', 'associated_jira',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    op.alter_column('upload_analysis', 'device_error',
               existing_type=mysql.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('upload_analysis', 'device_error',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    op.alter_column('upload_analysis', 'associated_jira',
               existing_type=mysql.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
