"""empty message

Revision ID: fbaedff1ebe9
Revises: 823e3df63271
Create Date: 2020-04-18 13:58:08.189594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fbaedff1ebe9'
down_revision = '823e3df63271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manual_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagfile', sa.String(length=200), nullable=False),
    sa.Column('rse_state', sa.String(length=100), nullable=False),
    sa.Column('build_package', sa.String(length=200), nullable=False),
    sa.Column('adk', sa.String(length=100), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('analysis', sa.String(length=1000), nullable=False),
    sa.Column('jira', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=200), nullable=False),
    sa.Column('device_error', sa.String(length=200), nullable=False),
    sa.Column('gsa', sa.String(length=200), nullable=False),
    sa.Column('hwtype', sa.String(length=200), nullable=False),
    sa.Column('motherboard', sa.String(length=200), nullable=False),
    sa.Column('dbmanager', sa.String(length=200), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('manual_analysis')
    # ### end Alembic commands ###
